# Generated by Django 5.1.5 on 2025-07-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0002_remove_inventario_precio_uniforme_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniforme',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
