# Generated by Django 5.1.5 on 2025-07-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0003_alter_uniforme_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniforme',
            name='precio',
        ),
        migrations.AddField(
            model_name='inventario',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
