# Generated by Django 5.1.5 on 2025-07-26 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0004_remove_uniforme_precio_inventario_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppInventario.inventario')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppInventario.venta')),
            ],
        ),
    ]
