# Generated by Django 5.1.5 on 2025-07-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0005_venta_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='codigo_barras',
            field=models.CharField(default=0, max_length=50, unique=True),
        ),
    ]
