# Generated by Django 5.1.5 on 2025-07-28 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0006_inventario_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppInventario.inventario'),
        ),
    ]
